### PR TITLE
Faster defaults

### LINKED ISSUE #230: Fuzzing with default settings is much slower than it needs to be
`cargo fuzz run` currently defaults to debug mode with Address Sanitizer. Debug mode in Rust is needlessly slow, easily 20x slower than release mode, and for fuzzing performance is critical. It would be a much better idea to default to release mode, but with debug assertions and overflow checks enabled.

The only reason to invoke actual debug mode is when reproducing the testcase and actually trying to debug it. So it'd be nice to add a flag `--debug` that forces debug mode and print it in the crash output, but this should be a non-breaking change in all other respects.

### PR DESCRIPTION
**Pull request by Shnatsel**
* Default to compiling in release mode with overflow checks and debug assertions enabled
    * Speeds up fuzzing ~10x
* ~~Add command line option for controlling overflow checks~~
* Add command line option for forcing debug mode without optimizations

Resolves #230

### CODE REVIEW

File: src/options.rs [hunk 1]
```diff
@@ -57,18 +57,26 @@ impl FromStr for Sanitizer {
 
 #[derive(Clone, Debug, StructOpt)]
 pub struct BuildOptions {
-    #[structopt(short = "O", long = "release")]
+    #[structopt(short = "D", long = "debug", conflicts_with = "release")]
+    /// Build artifacts in debug mode, without optimizations
+    pub debug: bool,
```
Comment (fitzgen) [inline src/options.rs:62]: Let's name this `--dev` to match the cargo profile name, and to avoid confusion like "how is this different from `--debug-assertions`?"

File: src/options.rs [hunk 2]
```diff
@@ -57,18 +57,26 @@ impl FromStr for Sanitizer {
...
-    /// Build target with verbose output from `cargo build`
-    #[structopt(short = "v", long = "verbose")]
-    pub verbose: bool,
-
     #[structopt(short = "a", long = "debug-assertions")]
     /// Build artifacts with debug assertions enabled (default if not -O)
     pub debug_assertions: bool,
 
+    #[structopt(short = "o", long = "overflow-checks")]
+    /// Build artifacts with overflow checks enabled (default if not -O)
```
Comment (fitzgen) [inline src/options.rs:73]: Regarding "default if not -O": right now, passing `-Oa` will enable overflow checks, is that not the case anymore after this PR? Many projects use `-Oa` and I'd be wary of making it lose the overflow checks. Do `debug-assertions` imply `overflow-checks` or are they disconnected now?

File: src/project.rs [hunk 3]
```diff
@@ -507,7 +507,7 @@ impl FuzzProject {
             }
 
             eprintln!(
-                "Reproduce with:\n\n\tcargo fuzz run {target} {artifact}\n",
+                "Reproduce with:\n\n\tcargo fuzz run --debug {target} {artifact}\n",
```
Comment (fitzgen) [inline src/project.rs:510]: Let's leave these without any flags for simplicity, and handle adding flags for them in #228

**Comment by fitzgen** [comment]
Tests are failing because they [look for bins at the `target/debug` path](https://github.com/rust-fuzz/cargo-fuzz/blob/87c36a1deee8ca9b550fe034623a7445d7e8c770/tests/tests/main.rs#L622) in various places, so they need to update to `target/release`.

Also, please add a test for the `--dev` (ne `--debug`) flag.

File: src/options.rs (hunk 2 above)
Comment (Shnatsel) [reply src/options.rs:73]: > right now, passing -Oa will enable overflow checks, is that not the case anymore after this PR?

That is still the case. The way these flags work is unchanged. Only the default state is altered, which is now equivalent to `-Ooa`

> Do debug-assertions imply overflow-checks or are they disconnected now?

I believe debug-assertions never implied overflow-checks, and enabling overflow-checks in release mode was not possible prior to this PR.

File: src/project.rs (hunk 3 above)
Comment (Shnatsel) [reply src/project.rs]: Done

File: src/options.rs (hunk 1 above)
Comment (Shnatsel) [reply src/options.rs]: Done

**Comment by Shnatsel** [comment]
I've fixed everything as requested. Will add a test for `--dev` shortly.

Do you have any ideas on how to clearly document that the default is `--release --debug-assertions --overflow-checks`? If I invoke `--help` it's not clear to me what the build mode will be if no parameters are passed.

Also, there are two changes that might be unexpected for end users:

 - This changes the coverage numbers. Now that a great deal of branches can be optimized out, the reported coverage is much lower (~2000 instead of ~7500 edges for `png` crate).
 - This changes the default location of the binary. If something was invoking the generated binary directly instead of via `cargo fuzz run`, that workflow will break.

Should we document this somewhere?

File: src/options.rs (hunk 2 above)
Comment (Shnatsel) [reply src/options.rs:73]: Oh wait, nevermind, I was confused. I'll have to test whether `-a` actually enables overflow checks or not.

Comment (Shnatsel) [reply src/options.rs:73]: Okay, I've tested it and turns out `--debug-assertions` already enables overflow checks, so there's no real need to have a separate flag for it. I'll drop the extra flag.

**Comment by Shnatsel** [comment]
Should be good to go now. Please take another look.

**Comment by fitzgen** [comment]
> Also, there are two changes that might be unexpected for end users:

I'm personally not too concerned with either of these, but we can bump to 0.8.x to be safe. @Manishearth any opinion here?

> Do you have any ideas on how to clearly document that the default is `--release --debug-assertions --overflow-checks`? If I invoke `--help` it's not clear to me what the build mode will be if no parameters are passed.

Perhaps in the before-help blurb for `cargo fuzz run`? https://github.com/rust-fuzz/cargo-fuzz/blob/87c36a1deee8ca9b550fe034623a7445d7e8c770/src/main.rs#L36-L43

And I think we would also want a custom template for `cargo fuzz build` like how `cargo fuzz run` has: https://github.com/rust-fuzz/cargo-fuzz/blob/87c36a1deee8ca9b550fe034623a7445d7e8c770/src/main.rs#L107

This way we could include the same blurb for both subcommands's help messages.

**Comment by nagisa** [comment]
> I'm personally not too concerned with either of these, but we can bump to 0.8.x to be safe.

There's not really a good reason to _not_ bump a "breaking" version number for binaries once there are larger changes to the interface. I vote bump.

**Comment by Shnatsel** [comment]
I've added a blurb about default build flags to the help text of both `cargo fuzz build` and `cargo fuzz run`. I've also added a blurb about sanitizers to `cargo fuzz build` after-help text, mostly so that I wouldn't have to create yet another help template.

**Comment by Manishearth** [comment]
@fitzgen I don't consider these to require a new major version

File: src/main.rs [hunk 4]
```diff
@@ -68,6 +72,17 @@ include:
     http://llvm.org/docs/LibFuzzer.html#dictionaries\
 ";
 
+const BUILD_BEFORE_HELP: &'static str = "\
+By default fuzz targets are built with optimizations equivalent to
+`cargo build --release`, but with debug assertions and overflow checks enabled.
```
Comment (frewsxcv) [inline src/main.rs:77]: > but with debug assertions and overflow checks enabled

which code in this pr is responsible for enabling debug assertions with release mode by default?
